<!DOCTYPE html>
<html xmlns:v-on="http://www.w3.org/1999/xhtml" xmlns:v-model="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8"/>
        <title>BBC Recipe system</title>
        <link href='/css/style.css' rel='stylesheet' type='text/css'>
        <link href='/css/layout.css' rel='stylesheet' type='text/css'>
        <script src="/vendor/jquery/dist/jquery.min.js"></script>
        <script src="/vendor/bootstrap-sass/assets/javascripts/bootstrap.min.js"></script>
        <script src="/vendor/vue/dist/vue.min.js"></script>
        <script src="/js/recipes.js"></script>
    </head>
    <body>
    <div class="container">
        <h1>BBC Features</h1>
        <h3>Recipes</h3>
        <div id="app" class="container">
            <div class="total">Total recipes: {{ +total }}</div>
            <div class='col-md-12' v-if="total < 1">
                <h4>Sorry, we currently have no recipes for you</h4>
            </div>
            <div class="col-md-12 top-bottom-buffer" v-if="total > 1">
                <h4>Filters</h4>
                <form class="form-inline" v-if="total > 0">
                    <div class="form-group">
                        <label for="Recipe">Recipe</label>
                        <input v-model="filter.main" v-on:change="filterData" type="text" class="form-control" id="recipe" placeholder="Lemon Chicken">
                    </div>
                    <div class="form-group">
                        <label for="ingredient">Ingredient</label>
                        <input v-model="filter.ingredient" v-on:change="filterData" type="text" class="form-control" id="ingredient" placeholder="Mustard">
                    </div>
                    <div class="form-group">
                        <label for="ingredient">Cooking time</label>
                        <select v-model="filter.time" v-on:change="filterData" class="form-control">
                            <option value="" selected>Select cooking time</option>
                            <option :value="time" v-for="time in buildTimeFilterData()" v-model:times>{{ time }} minutes</option>
                        </select>
                    </div>
                </form>
                <div class="col-md-12 top-bottom-buffer" v-if="total > 1">
                    <button type="button" class="btn btn-success" v-on:click="getStarred">Show starred recipes</button>
                </div>
            </div>
            <div class="col-md-12">
                <div class='col-md-12' v-if="total > 0 && items.length < 1 && !starsFilter">
                    <h4>Sorry, nothing matched your filter term</h4>
                </div>
                <div class='col-md-12' v-if="total > 0 && items.length < 1 && starsFilter">
                    <h4>Sorry, you don't currently have any starred recipes, get started by starring recipes you like</h4>
                </div>
                <div class="row">
                    <recipe-item v-for="item in items" v-bind:recipe="item"></recipe-item>
                </div>
                <div class="row" v-if="pages.length > 1">
                    <ul class="pagination">
                        <recipe-paginator v-for="page in pages" v-bind:page="page"></recipe-paginator>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    </body>
</html>
