<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>BBC Recipe system</title>
        <link href='/css/style.css' rel='stylesheet' type='text/css'>
        <link href='/css/layout.css' rel='stylesheet' type='text/css'>
        <script src="/vendor/jquery/dist/jquery.min.js"></script>
        <script src="/vendor/bootstrap-sass/assets/javascripts/bootstrap.min.js"></script>
        <script src="/vendor/vue/dist/vue.min.js"></script>
        <script src="/js/scripts.js"></script>
    </head>
    <body>
    <div class="container">
        <h1>BBC Features</h1>
        <h3>Recipes</h3>
        <div id="app" class="container">
            <div class="total">Total recipes: {{ +total }}</div>
            <div class='col-md-12' v-if="total < 1">
                <h4>Sorry, we currently have no recipes for you</h4>
            </div>
            <div class='col-md-12' v-if="total > 0 && items.length < 1">
                <h4>Sorry, nothing matched your filter term</h4>
            </div>
            <div class="row">
                <recipe-item v-for="item in items" v-bind:recipe="item"></recipe-item>
            </div>
        </div>
    </div>
    </body>
</html>
