<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>BBC Recipe system</title>
        <link href='/css/style.css' rel='stylesheet' type='text/css'>
        <link href='/css/layout.css' rel='stylesheet' type='text/css'>
        <script src="/vendor/jquery/dist/jquery.min.js"></script>
        <script src="/vendor/bootstrap-sass/assets/javascripts/bootstrap.min.js"></script>
        <script src="/vendor/vue/dist/vue.min.js"></script>
        <script src="/js/scripts2.js"></script>
        <script type="text/javascript">
            var recipeId = '<?= $id ?>';
        </script>
    </head>
    <body>
    <div class="container">
        <h1>BBC Features</h1>
        <h3>Recipe</h3>
        <div id="app" class="container">
            <div class='col-md-12' v-if="!item">
                <h4>Sorry, this recipe doesn't exist or may have been removed</h4>
            </div>
            <h4 v-if="item">{{item.name}}</h4>
        </div>
    </div>
    </body>
</html>
